name: Build

on:
  - push
  - pull_request
  - workflow_dispatch

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3.5.3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Build
        run: dotnet publish -c ${{env.BUILD_TYPE}}

      - name: Upload Artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          path: src/bin
